node {
    stage('Checkout code') {
    git 'https://github.com/deeanosaure/demoapp.git'
}
    stage('Build') {
    sh "mvn clean install"
}
    stage('Activate Chuck Norris') {
    chuckNorris()
}

}
